---
- name: Download Microsoft repo key
  get_url:
    url: https://packages.microsoft.com/keys/microsoft.asc
    dest: /etc/apt/keyrings/microsoft.asc
    mode: '0644'
  register: microsoft_key
  become: true

- name: Add Microsoft repo
  apt_repository:
    state: present
    repo: "deb [arch=amd64 signed-by={{ microsoft_key.dest }}] https://packages.microsoft.com/repos/azure-cli/ {{ codename }} main"
    filename: azure-cli
  become: true

- name: Install Azure CLI
  apt:
    name: azure-cli
    state: present
    update_cache: true
  become: true