---
- name: Add Docker repo key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
  become: true

- name: Add Docker repo
  apt_repository:
    repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_facts['distribution_release'] }} stable"
    mode: 0644
    filename: docker
  become: true

- name: Ensure Docker is installed
  apt:
    state: present
    update_cache: true
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
  become: true

- name: Add Trivy repo key
  apt_key:
    url: https://aquasecurity.github.io/trivy-repo/deb/public.key
    state: present
  become: true

- name: Add Trivy repo
  apt_repository:
    state: present
    repo: "deb https://aquasecurity.github.io/trivy-repo/deb focal main" # No hirsute repo
    mode: 0644
    filename: trivy
  become: true

- name: Install Trivy
  apt:
    name: trivy
    state: present
    update_cache: true
  become: true