---
- name: Add Docker repo key
  get_url:
    url: https://download.docker.com/linux/ubuntu/gpg
    dest: /etc/apt/keyrings/docker.asc
    mode: '0644'
  register: docker_key
  become: true

- name: Add Docker repo
  apt_repository:
    repo: "deb [arch=amd64 signed-by={{ docker_key.dest }}] https://download.docker.com/linux/ubuntu {{ codename }} stable"
    mode: 0644
    filename: docker
  become: true

- name: Ensure Docker is installed
  apt:
    state: present
    update_cache: true
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
  become: true

- name: Add Trivy repo key
  get_url:
    url: https://aquasecurity.github.io/trivy-repo/deb/public.key
    dest: /etc/apt/keyrings/trivy.asc
    mode: '0644'
  register: trivy_key
  become: true

- name: Add Trivy repo
  apt_repository:
    state: present
    repo: "deb [signed-by={{ trivy_key.dest }}] https://aquasecurity.github.io/trivy-repo/deb {{ codename }} main" # No hirsute repo
    mode: 0644
    filename: trivy
  become: true

- name: Install Trivy
  apt:
    name: trivy
    state: present
    update_cache: true
  become: true