---
- name: Download HashiCorp repo key
  get_url:
    url: https://apt.releases.hashicorp.com/gpg
    dest: /etc/apt/keyrings/hashicorp.asc
    mode: '0644'
  register: hashicorp_key
  become: true

- name: Add HashiCorp repo
  apt_repository:
    state: present
    repo: "deb [signed-by={{ hashicorp_key.dest }}] https://apt.releases.hashicorp.com {{ ansible_distribution_release }} main"
    filename: hashicorp
  become: true

- name: Ensure Terraform and Vault are installed
  apt:
    state: present
    update_cache: true
    name:
      - terraform
      - vault
  become: true

- name: Configure tf alias
  lineinfile:
    path: "{{ zsh_conf }}"
    line: "alias tf=terraform"
    state: present