---
- name: Ensure JDK 11, 17 & Maven installed
  apt:
    state: present
    name:
      - openjdk-11-jdk
      - openjdk-17-jdk
      - maven
  become: true

- name: Install IntelliJ IDE
  snap:
    state: present
    name: intellij-idea-ultimate
    classic: true
  become: true
  when: ansible_facts['distribution'] == "Ubuntu"