---
- name: Add kubernetes repo key
  apt_key:
    url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
    state: present
  become: true

- name: Add kubernetes repo
  apt_repository:
    state: present
    repo: "deb https://apt.kubernetes.io/ kubernetes-xenial main" # No hirsute Release
    mode: 0644
    filename: kubectl
  become: true

- name: Install kubectl
  apt:
    name: kubectl
    state: present
    update_cache: true
  become: true

- name: Add autocompletion to ZSH
  lineinfile:
    path: "{{ zsh_conf }}"
    line: "{{ item }}"
    state: present
  loop:
    - source <(kubectl completion zsh)
    - complete -F __start_kubectl k
    - alias k='kubectl'
    - alias kdebug='k run -it ${USER}-debug --image=alpine --rm'
    - function kn(){ kubectl config set-context --current --namespace=$1 }

- name: Add Helm repo key
  apt_key:
    url: https://baltocdn.com/helm/signing.asc
    state: present
  become: true

- name: Add Helm repo
  apt_repository:
    state: present
    repo: "deb https://baltocdn.com/helm/stable/debian/ all main" # No hirsute Release
    mode: 0644
    filename: helm
  become: true

- name: Install Helm
  apt:
    name: helm
    state: present
    update_cache: true
  become: true