---
- name: Add kubernetes repo key
  get_url:
    url: "https://pkgs.k8s.io/core:/stable:/v{{ kubernetes_version }}/deb/Release.key"
    dest: /etc/apt/keyrings/kubernetes.asc
    mode: '0644'
  register: kubernetes_key
  become: true

- name: Add kubernetes repo
  apt_repository:
    state: present
    repo: "deb [signed-by={{ kubernetes_key.dest }}] https://pkgs.k8s.io/core:/stable:/v{{ kubernetes_version }}/deb/ /"
    mode: 0644
    filename: kubernetes
  become: true

- name: Install kubectl
  apt:
    name: kubectl
    state: present
    update_cache: true
  become: true

- name: Add autocompletion to ZSH
  lineinfile:
    path: "{{ zsh_conf }}"
    line: "{{ item }}"
    state: present
  loop:
    - source <(kubectl completion zsh)
    - complete -F __start_kubectl k
    - alias k='kubectl'
    - alias kdebug='k run -it ${USER}-debug --image=alpine --rm'
    - function kn(){ kubectl config set-context --current --namespace=$1 }

- name: Add Helm repo key
  get_url:
    url: https://baltocdn.com/helm/signing.asc
    dest: /etc/apt/keyrings/helm.asc
    mode: '0644'
  register: helm_key
  become: true

- name: Add Helm repo
  apt_repository:
    state: present
    repo: "deb [signed-by={{ helm_key.dest }}] https://baltocdn.com/helm/stable/debian/ all main"
    mode: 0644
    filename: helm
  become: true

- name: Install Helm
  apt:
    name: helm
    state: present
    update_cache: true
  become: true