---
- set_fact:
    node_version: '14'

- name: Add NodeJS apt repo key
  apt_key:
    state: present
    url: https://deb.nodesource.com/gpgkey/nodesource.gpg.key
  become: true

- name: Add NodeJS {{ node_version }} apt repo
  apt_repository:
    state: present
    repo: "{{ item }}"
    filename: nodejs
  become: true
  loop:
    - "deb https://deb.nodesource.com/node_{{ node_version }}.x {{ ansible_facts['distribution_release'] }} main"
    - "deb-src https://deb.nodesource.com/node_{{ node_version }}.x {{ ansible_facts['distribution_release'] }} main"

- name: Install NodeJS LTS
  apt:
    name: nodejs
    state: present
    update_cache: true
  become: true